//LOCALHOST
### Get All Players
GET http://localhost:8080/players

### Get Players by Id
GET http://localhost:8080/players/6843df5efa45d788de1f01b7

### Create Player
Post http://localhost:8080/players/ HTTP/1.1
Content-type: application/json

{
      "name": "Bradley",
    "position": "Defender",
    "team": "Thunders FC",
    "age": 23,
    "appearance": 6,
    "goals": 0,
    "assists": 0
  }



### Put/Update Contact
Put http://localhost:8080/players/6843df5efa45d788de1f01b7 HTTP/1.1
Content-type: application/json

{
     "name": "Proud Namwera",
    "position": "Midfielder",
    "team": "Thunders FC",
    "age": 23,
    "appearance": 6,
    "goals": 1,
    "assists": 5
  }


### Delete Contact
DELETE  http://localhost:8080/players/6844532dc39efca254e63877 HTTP/1.1


